# Generated by Django 4.2.11 on 2025-12-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_voucherbatch_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='duration_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('months', 'Months')], default='days', help_text='Unit of time for the duration', max_length=10),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='duration_value',
            field=models.IntegerField(default=30, help_text='Duration value (e.g., 30 for 30 days)'),
        ),
        migrations.AlterField(
            model_name='billingplan',
            name='duration_days',
            field=models.IntegerField(default=30, help_text='Legacy: Subscription duration in days'),
        ),
    ]
