# Generated by Django 4.2.11 on 2025-12-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        ('billing', '0004_billingplan_duration_unit_billingplan_duration_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='routers',
            field=models.ManyToManyField(blank=True, help_text='Routers where this plan should be provisioned', related_name='billing_plans', to='network.router'),
        ),
    ]
