# Generated by Django 4.2.11 on 2026-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_voucher_plan_voucherbatch_plan_alter_voucher_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingplan',
            name='service_type',
            field=models.CharField(choices=[('pppoe', 'PPPoE'), ('hotspot', 'Hotspot'), ('static', 'Static IP')], max_length=10),
        ),
    ]
