# Generated by Django 4.2.11 on 2026-01-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_voucher_plan_voucherbatch_plan_alter_voucher_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerecord',
            name='download_speed_mbps',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='upload_speed_mbps',
            field=models.FloatField(default=0.0),
        ),
    ]
