# Generated by Django 4.2.11 on 2026-01-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_usagerecord_download_speed_mbps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
