# Generated by Django 4.2.11 on 2026-08-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_billingplan_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
