# Generated by Django 4.2.11 on 2026-08-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_transaction_mpesa_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('balance', 'Account Balance'), ('other', 'Other')], default='mpesa', max_length=10),
        ),
    ]
