# Generated by Django 4.2.11 on 2025-12-17 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=8728)),
                ('use_ssl', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Router',
                'verbose_name_plural': 'Routers',
                'db_table': 'routers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PPPoESecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('local_address', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10)),
                ('synced_to_router', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_secret', to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_secrets', to='network.router')),
            ],
            options={
                'verbose_name': 'PPPoE Secret',
                'verbose_name_plural': 'PPPoE Secrets',
                'db_table': 'pppoe_secrets',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='HotspotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('uptime_limit', models.CharField(blank=True, max_length=50, null=True)),
                ('bytes_limit', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10)),
                ('synced_to_router', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_user', to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_users', to='network.router')),
            ],
            options={
                'verbose_name': 'Hotspot User',
                'verbose_name_plural': 'Hotspot Users',
                'db_table': 'hotspot_users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('pppoe', 'PPPoE'), ('hotspot', 'Hotspot')], max_length=10)),
                ('session_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('uptime_seconds', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='network.router')),
            ],
            options={
                'verbose_name': 'Active Session',
                'verbose_name_plural': 'Active Sessions',
                'db_table': 'active_sessions',
                'ordering': ['-start_time'],
                'unique_together': {('router', 'session_id')},
            },
        ),
    ]
