# Generated by Django 4.2.11 on 2026-07-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='dns_servers',
            field=models.CharField(default='8.8.8.8,8.8.4.4', max_length=100),
        ),
        migrations.AddField(
            model_name='router',
            name='hotspot_subnet',
            field=models.CharField(default='10.5.50.0/24', help_text='CIDR subnet for Hotspot clients, e.g. 10.5.50.0/24', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='pppoe_subnet',
            field=models.CharField(default='10.5.60.0/24', help_text='CIDR subnet for PPPoE clients, e.g. 10.5.60.0/24', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='provisioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='router',
            name='provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
