# Generated by Django 4.2.11 on 2026-01-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterInterfaceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=100)),
                ('tx_bps', models.BigIntegerField(default=0)),
                ('rx_bps', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_stats', to='network.router')),
            ],
            options={
                'verbose_name': 'Router Interface Stat',
                'verbose_name_plural': 'Router Interface Stats',
                'db_table': 'router_interface_stats',
                'unique_together': {('router', 'interface_name')},
            },
        ),
    ]
