# Generated by Django 4.2.11 on 2026-07-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_router_dns_servers_router_hotspot_subnet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='pre_provision_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='pre_provision_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
