# Generated by Django 4.2.11 on 2026-07-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_router_pre_provision_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='portal_url',
            field=models.CharField(blank=True, default='https://isp.hasalioma.online/portal', help_text='External captive portal URL, e.g. https://yourdomain.com/portal', max_length=200),
        ),
    ]
