# Generated by Django 4.2.11 on 2026-07-27 18:53

import apps.network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_router_portal_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='portal_url',
            field=models.CharField(blank=True, default=apps.network.models.default_portal_url, help_text='External captive portal URL, e.g. https://yourdomain.com/portal', max_length=200),
        ),
    ]
