# Generated by Django 4.2.11 on 2025-12-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hotspot_mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
