# Generated by Django 4.2.11 on 2026-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('technician', 'Technician'), ('sales', 'Sales Person')], default='admin', max_length=20),
        ),
    ]
