# Generated by Django 4.2.11 on 2026-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='static_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='service_type',
            field=models.CharField(choices=[('pppoe', 'PPPoE'), ('hotspot', 'Hotspot'), ('both', 'Both'), ('static', 'Static IP')], default='pppoe', max_length=10),
        ),
    ]
