# Generated by Django 4.2.11 on 2026-08-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_static_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
