# Generated by Django 4.2.11 on 2026-08-02 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0007_alter_billingplan_service_type'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2BPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('transaction_type', models.CharField(blank=True, max_length=50)),
                ('transaction_time', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_short_code', models.CharField(blank=True, max_length=20)),
                ('bill_ref_number', models.CharField(blank=True, max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('org_account_balance', models.CharField(blank=True, max_length=50)),
                ('third_party_trans_id', models.CharField(blank=True, max_length=100)),
                ('msisdn', models.CharField(blank=True, max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('activated', 'Activated'), ('matched_no_plan', 'Matched, No Plan'), ('unmatched', 'Unmatched'), ('error', 'Error')], default='unmatched', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c2b_payment', to='billing.transaction')),
                ('matched_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c2b_payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c2b_payments', to='billing.subscription')),
            ],
            options={
                'verbose_name': 'C2B Payment',
                'verbose_name_plural': 'C2B Payments',
                'db_table': 'c2b_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
