# Generated by Django 4.2.11 on 2026-08-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_c2bpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c2bpayment',
            name='msisdn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
